version: '3'
services:
  web:
    image: iiiepe/apache-drupal6
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
